### ISSUE TITLE
Add Github Actions to the Project

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#26]
## Type

Feature

## Description

Add Github Actions to the Project. 

- [ ] Label all Issue created as `CH20`
- [ ] Greet the User creating any Issue/PR

## Tools

- Github Actions

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

### Motivation

I am literally tired adding Tags to respective Issues.

**Comment by chttrjeankr** [comment]
I think I can take this up :smiley:  @HarshCasper

**Comment by HarshCasper** [comment]
I have assigned it to you @chttrjeankr

**Comment by chttrjeankr** [comment]
![image](https://user-images.githubusercontent.com/39518771/90372108-84213200-e08d-11ea-9543-be407c45f2c2.png)
@HarshCasper, @sarthakkundra I think this is because of some restrictions on what kind of actions are allowed in the organization.

Maybe [this](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/disabling-or-limiting-github-actions-for-your-organization) page will help to sort it out.
@bhadreshpsavani made the new assignment in this [issue](https://github.com/HakinCodes/Malaria-Detection/issues/31) on which the action didn't run.

**Comment by sarthakkundra** [comment]
@sarthakkundra Yes I'm looking into it
