### ISSUE TITLE
Create an EDA Documentation Summary

### ISSUE THREAD

**Issue by HarshCasper** [HakinCodes/Malaria-Detection#50]
## Type

Advancement 

## Description

@kritikaparmar-programmer has done an excellent job in creating an EDA on the Malarial Cell Dataset. We need a Markdown Documentation that can help us form our Wiki later using the EDA contributed by her. You can check out the Pull Request [here](https://github.com/HakinCodes/Malaria-Detection/pull/48) and create basic documentation to explore the basic intuition behind the Dataset.

## Tools

- Markdown

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes 

### Motivation

To later form part of our Wiki

**Comment by cnduc** [comment]
I would like to work on this. Please assign it to me. @HarshCasper

**Comment by sarthakkundra** [comment]
@cnduc  Assigned :) you have 7 days to work on the issue.

**Comment by cnduc** [comment]
@HarshCasper Hello, I am done working with the documentation, but i am not sure how to push the files here. Can some help me with push and pull requests.  Thanks in advance.

**Comment by sarthakkundra** [comment]
@cnduc First your have to push code to your forked repository for that follow these commands.
1. Navigate to the folder in the cmd line using the command 'cd' For eg :- cd desktop/Malaria
2. Then write the command 'git add . ' this will add all the new/modified folder in a stack ready to be uploaded.
3. At any point of time if you have any doubt if all the files are there or not you can check that by writing ' git status'
4. After that commit those files using git commit -m 'Add an explanatory message here like Updated Readme with...'
5. Finally ' git push ' to upload the changes to your fork
Once this is done successfully refer to this [https://docs.github.com/en/enterprise/2.15/user/articles/creating-a-pull-request-from-a-fork](article) to create a pull request so that we can checkout your changes. Hope this would've answered all the queries :)

**Comment by cnduc** [comment]
@sarthakkundra Hi, i tried adding the repositoty using git add command. It throws a fatal error(not a git repository or any of the parent directories). I have already uploaded files in a new repository.

**Comment by HarshCasper** [comment]
@cnduc If you have further issues, kindly contact me on Slack
